
  create table "public"."testdb" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "email" character varying
      );


alter table "public"."testdb" enable row level security;

CREATE UNIQUE INDEX "test db_pkey" ON public.testdb USING btree (id);

alter table "public"."testdb" add constraint "test db_pkey" PRIMARY KEY using index "test db_pkey";

grant delete on table "public"."testdb" to "anon";

grant insert on table "public"."testdb" to "anon";

grant references on table "public"."testdb" to "anon";

grant select on table "public"."testdb" to "anon";

grant trigger on table "public"."testdb" to "anon";

grant truncate on table "public"."testdb" to "anon";

grant update on table "public"."testdb" to "anon";

grant delete on table "public"."testdb" to "authenticated";

grant insert on table "public"."testdb" to "authenticated";

grant references on table "public"."testdb" to "authenticated";

grant select on table "public"."testdb" to "authenticated";

grant trigger on table "public"."testdb" to "authenticated";

grant truncate on table "public"."testdb" to "authenticated";

grant update on table "public"."testdb" to "authenticated";

grant delete on table "public"."testdb" to "postgres";

grant insert on table "public"."testdb" to "postgres";

grant references on table "public"."testdb" to "postgres";

grant select on table "public"."testdb" to "postgres";

grant trigger on table "public"."testdb" to "postgres";

grant truncate on table "public"."testdb" to "postgres";

grant update on table "public"."testdb" to "postgres";

grant delete on table "public"."testdb" to "service_role";

grant insert on table "public"."testdb" to "service_role";

grant references on table "public"."testdb" to "service_role";

grant select on table "public"."testdb" to "service_role";

grant trigger on table "public"."testdb" to "service_role";

grant truncate on table "public"."testdb" to "service_role";

grant update on table "public"."testdb" to "service_role";


